# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  serviceConnection: 'acr-dockerconnection'
  imageName: 'vehiculesapi'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildPush
  displayName: Build and push image
  jobs:
  - job: BuildPush
    displayName: Build and push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(serviceConnection)'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/AutoRapide/src/Dockerfile'
        tags: |
          $(tag)
